databases:
  - name: jurneyhub_DB
    databaseName: jurneyhub_db_bvan
    user: jurneyhub1
    region: singapore

services:
  - type: web
    name: jurneyhub1
    env: ruby
    region: singapore
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: <%= ENV['DATABASE_URL'] %>
        fromDatabase:
          name: jurneyhub_DB
          property: connectionString
      - key: <%= ENV['RAILS_MASTER_KEY'] %>
        sync: false
